// This file is used to define the Genkit flow for generating cat explanations for each portfolio section.

'use server';

/**
 * @fileOverview Generates explanations for each section of the portfolio using a conversational AI.
 *
 * - generateCatExplanations - A function that generates explanations for portfolio sections.
 * - GenerateCatExplanationsInput - The input type for the generateCatExplanations function.
 * - GenerateCatExplanationsOutput - The return type for the generateCatExplanations function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const GenerateCatExplanationsInputSchema = z.object({
  sectionName: z.string().describe('The name of the portfolio section.'),
  sectionContent: z.string().describe('The content of the portfolio section.'),
});

export type GenerateCatExplanationsInput = z.infer<typeof GenerateCatExplanationsInputSchema>;

const GenerateCatExplanationsOutputSchema = z.object({
  explanation: z.string().describe('The explanation generated by the AI for the portfolio section.'),
});

export type GenerateCatExplanationsOutput = z.infer<typeof GenerateCatExplanationsOutputSchema>;

export async function generateCatExplanations(
  input: GenerateCatExplanationsInput
): Promise<GenerateCatExplanationsOutput> {
  return generateCatExplanationsFlow(input);
}

const generateCatExplanationsPrompt = ai.definePrompt({
  name: 'generateCatExplanationsPrompt',
  input: {schema: GenerateCatExplanationsInputSchema},
  output: {schema: GenerateCatExplanationsOutputSchema},
  prompt: `You are a helpful 3D cat guide, explaining different sections of a portfolio.

  Based on the section name and content, generate a concise and engaging explanation.

  Section Name: {{{sectionName}}}
  Section Content: {{{sectionContent}}}

  Explanation:`,
});

const generateCatExplanationsFlow = ai.defineFlow(
  {
    name: 'generateCatExplanationsFlow',
    inputSchema: GenerateCatExplanationsInputSchema,
    outputSchema: GenerateCatExplanationsOutputSchema,
  },
  async input => {
    const {output} = await generateCatExplanationsPrompt(input);
    return output!;
  }
);
