
export const projects = [
  {
    id: "project-1",
    title: "Rapido UI/UX Redesign",
    description: "An interactive prototype redesign for Rapido, transforming travel into a premium digital experience.",
    longDescription: "The Rapido UI/UX redesign project was a deep dive into crafting a premium, end-to-end travel experience. Our focus was to transform the functional process of booking a ride into a seamless and sophisticated journey. By integrating a clean, intuitive interface with elegant visual cues, we elevated the user experience to reflect the speed and convenience of modern travel, with a touch of luxury. Every interaction was meticulously designed to be effortless, ensuring that users feel confident and catered to from the moment they open the app to their final destination.",
    tags: ["UI/UX Design", "Interactive Prototype", "Figma"],
    thumbnailId: "project-1-thumb",
    imageIds: ["rapido-home", "rapido-travel", "rapido-flight"],
  },
  {
    id: "project-2",
    title: "LOSMO",
    description: "A refined emblem of luxury for a perfume brand, crafted to express elegance, artistry, and timeless sophistication.",
    longDescription: "Crafting the LOSMO logo was an exercise in pure elegance. The goal was to create a mark that felt both timeless and modern, embodying the essence of a luxury perfume brand. Through refined typography and a minimalist aesthetic, the final design speaks to an audience that appreciates artistry, quality, and understated sophistication. It's more than a logo; it's a signature of luxury that adorns every bottle and correspondence, promising an experience of refined scent and unparalleled class.",
    tags: ["Logo Design", "Branding", "Luxury"],
    thumbnailId: "project-2-thumb",
    imageIds: ["losmo-homepage", "losmo-woody", "losmo-floral", "losmo-collection", "losmo-candles", "losmo-product", "losmo-gift", "losmo-story"],
  },
  {
    id: "project-3",
    title: "LOGO",
    description: "Breathing new life into a brand's identity with a modern, impactful, and versatile logo redesign.",
    longDescription: "This project involved taking an existing brand identity and breathing new life into it. The redesign focused on modernizing the visual language while honoring the brand's core values. The result is an impactful and versatile logo that works beautifully across all digital and print applications, giving the brand a fresh platform for future growth.",
    tags: ["Logo redesign"],
    thumbnailId: "project-3-thumb",
    imageIds: ["logo-redesign-1", "logo-redesign-2", "logo-redesign-3", "logo-redesign-4", "logo-redesign-5"],
  },
  {
    id: "project-logo-redesign",
    title: "LOGO",
    description: "A comprehensive showcase of brand revitalizations, from corporate giants to boutique labels.",
    longDescription: "This collection features meticulous redesigns for brands like Air India, Café Coffee Day, and Medimix. Each project was an exercise in balancing heritage with contemporary visual trends, ensuring that the brand identity remains recognizable while feeling fresh, dynamic, and future-proof. The focus was on clarity, scalability, and emotional resonance.",
    tags: ["Logo redesign", "Case Study"],
    thumbnailId: "redesign-air-india",
    imageIds: ["redesign-air-india", "redesign-ccd-1", "redesign-ccd-2", "redesign-indigo", "redesign-medimix-1", "redesign-medimix-2"],
  },
  {
    id: "project-5",
    title: "Packaging",
    description: "Crafting memorable unboxing experiences with stunning package designs and redesigns that capture brand essence.",
    longDescription: "Packaging is the first physical touchpoint a customer has with a brand. This project focused on creating a memorable unboxing experience through stunning package design. We worked to ensure the packaging not only protected the product but also captured the brand's essence, turning a simple box into a powerful marketing tool and a delightful customer experience.",
    tags: ["Packaging", "Branding", "Product Design"],
    thumbnailId: "project-5-thumb",
    imageIds: ["pkg-design-bag", "pkg-design-box-floral", "pkg-design-box-main", "pkg-design-candle", "pkg-design-gift-1", "pkg-design-gift-2"],
  },
  {
    id: "project-packaging-redesign",
    title: "Packaging",
    description: "Reimagining established products with modern, sustainable, and consumer-focused packaging solutions.",
    longDescription: "This series explores the transformation of established brand packaging. By analyzing consumer behavior and modern retail environments, we developed redesigns that improve shelf presence, sustainability, and ease of use, all while maintaining the brand's recognizable heritage.",
    tags: ["Packaging Redesign", "Sustainability"],
    thumbnailId: "pkg-redesign-box",
    imageIds: ["pkg-redesign-box", "pkg-redesign-loreal", "pkg-redesign-pack", "pkg-redesign-video"],
  },
  {
    id: "project-6",
    title: "Type specimen",
    description: "Exploring the art of typography with a detailed type specimen, showcasing the beauty and versatility of a chosen typeface.",
    longDescription: "Typography is the cornerstone of good design. This project is a deep exploration into the art of the letterform through an interactive 3D type specimen. Designed as a physical book experience, this specimen allows you to interact with the typography, experiencing the tone, hierarchy, and emotion of the typeface through tactile, fluid movements.",
    tags: ["Typography", "Graphic Design"],
    thumbnailId: "project-6-thumb",
    imageIds: ["typespec-1", "typespec-2", "typespec-3", "typespec-4", "typespec-5"],
  },
];
