export const projects = [
  {
    id: "project-1",
    title: "Rapido UI/UX Redesign",
    description: "A complete UI/UX overhaul for the popular bike taxi app, focusing on a modern and user-friendly experience.",
    longDescription: "The Rapido UI/UX redesign project was a deep dive into crafting a premium, end-to-end travel experience. Our focus was to transform the functional process of booking a ride into a seamless and sophisticated journey. By integrating a clean, intuitive interface with elegant visual cues, we elevated the user experience to reflect the speed and convenience of modern travel, with a touch of luxury. Every interaction was meticulously designed to be effortless, ensuring that users feel confident and catered to from the moment they open the app to their final destination.",
    tags: ["UI/UX Design", "Mobile App", "Figma"],
    thumbnailId: "project-1-thumb",
    imageIds: ["rapido-1", "rapido-2", "rapido-3", "rapido-4", "rapido-5"],
  },
  {
    id: "project-2",
    title: "LOSMO",
    description: "A refined emblem of luxury for a perfume brand, crafted to express elegance, artistry, and timeless sophistication.",
    longDescription: "Crafting the LOSMO logo was an exercise in pure elegance. The goal was to create a mark that felt both timeless and modern, embodying the essence of a luxury perfume brand. Through refined typography and a minimalist aesthetic, the final design speaks to an audience that appreciates artistry, quality, and understated sophistication. It's more than a logo; it's a signature of luxury that adorns every bottle and correspondence, promising an experience of refined scent and unparalleled class.",
    tags: ["Logo Design", "Branding", "Luxury"],
    thumbnailId: "project-2-thumb",
    imageIds: ["losmo-2", "losmo-3", "losmo-7", "losmo-5", "losmo-4", "losmo-8", "losmo-6", "losmo-1"],
  },
  {
    id: "project-3",
    title: "Logo Re-Design",
    description: "Breathing new life into a brand's identity with a modern, impactful, and versatile logo redesign.",
    longDescription: "This project involved taking an existing brand identity and breathing new life into it. The redesign focused on modernizing the visual language while honoring the brand's core values. The result is an impactful and versatile logo that works beautifully across all digital and print applications, giving the brand a fresh platform for future growth.",
    tags: ["Logo Design", "Branding"],
    thumbnailId: "project-3-thumb",
    imageIds: [],
  },
  {
    id: "project-5",
    title: "Package design and redesign",
    description: "Crafting memorable unboxing experiences with stunning package designs and redesigns that capture brand essence.",
    longDescription: "Packaging is the first physical touchpoint a customer has with a brand. This project focused on creating a memorable unboxing experience through stunning package design. We worked to ensure the packaging not only protected the product but also captured the brand's essence, turning a simple box into a powerful marketing tool and a delightful customer experience.",
    tags: ["Packaging", "Branding", "Product Design"],
    thumbnailId: "project-5-thumb",
    imageIds: [],
  },
  {
    id: "project-6",
    title: "Type specimen",
    description: "Exploring the art of typography with a detailed type specimen, showcasing the beauty and versatility of a chosen typeface.",
    longDescription: "Typography is the cornerstone of good design. This project is a deep exploration into the art of the letterform through a detailed type specimen. It showcases the beauty, versatility, and unique character of a chosen typeface, demonstrating its potential to communicate tone, hierarchy, and emotion in visual design.",
    tags: ["Typography", "Graphic Design"],
    thumbnailId: "project-6-thumb",
    imageIds: [],
  },
];
